name: CI

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
      
    - name: Install build tools using NPM
      uses: actions/setup-node@v1
    - run: npm install jsonlint -g

    - name: Run jsonlint
      run: jsonlint dnsTemplate.json

name: AzureLogin

on: [push]

jobs: 
  build-and-deploy: 
    runs-on: ubuntu-latest
    steps:

    - uses: azure/actions/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

     - run: |
        az webapp list --query "[?state=='Running']"
