name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
      
    - name: Install build tools using NPM
      uses: actions/setup-node@v1
    - run: npm install jsonlint -g

    - name: Run jsonlint
      run: jsonlint dnsTemplate.json
