name: CI

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
      
    - name: Install build tools using NPM
      uses: actions/setup-node@v1
    - run: npm install jsonlint -g

    - name: Run jsonlint
      run: jsonlint dnsTemplate.json
      
    - action: "Manage Azure Resources" {
    - uses: "Azure/github-actions/arm@master"
    - env: = {
    AZURE_RESOURCE_GROUP = "<Dev_Test_group>"
    AZURE_TEMPLATE_LOCATION = "<https://github.com/workingtalent/azure-dns/blob/master/dnsTemplate.json>"
    AZURE_TEMPLATE_PARAM_FILE = "<URL or Relative path in your repository>"
  }
   - needs: = ["azure login"]
}
